spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DataBaseName=ACG
    username: sa
    password: root
  thymeleaf:
    cache: false
#  mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml #mapper的映射文件
  type-aliases-package: com.example.xjlacgapp.pojo
#druid数据库连接池
type: com.alibaba.druid.pool.DruidDataSource
#端口号
server:
  port: 8080
